### ISSUE TITLE
[Feature] Door kunnen klikken op klas/docent/lokaal

### ISSUE THREAD

**Issue by matthijs186** [HetIsNiels/ndat-rooster#11]
Als je een rooster open hebt, kan je doorklikken op klas/docent/lokaal om naar die roosterpagina te gaan.

**Comment by nielsvanvelzen** [comment]
https://github.com/HetIsNiels/ndat-rooster/commit/52cc3cec2b35b5681cc0bf7f6aed8a4f51eb32e4
