### ISSUE TITLE
Links naar andere roosters werken niet

### ISSUE THREAD

**Issue by matthijs186** [HetIsNiels/ndat-rooster#16]
Na de laatste update werken de links naar andere roosters niet meer. De app lijkt de pagina proberen op te halen maar valt daarna toch weer prompt terug.

**Comment by nielsvanvelzen** [comment]
Als ik op een ander item klik wordt deze wel geladen maar dat is niet zichtbaar op template niveau en het wordt ook niet opgeslagen. Dit was de bedoeling om het snel te laten werken. Uit eindelijk zal het in een overlay moeten komen.

Maar het rooster zelf bevat wel de inhoud die je zou willen zien.

**Comment by matthijs186** [comment]
Dat vermoedde ik al.
