### ISSUE TITLE
Meerdere klassen kunnen selecteren

### ISSUE THREAD

**Issue by matthijs186** [HetIsNiels/ndat-rooster#2]
Momenteel wordt alleen het dagrooster getoond van Z ZAO14A. Het zou handig zijn als er van meerdere klassen het rooster kan worden weergegeven.

**Comment by nielsvanvelzen** [comment]
Ik ben hiermee begonnen in https://github.com/HetIsNiels/ndat-rooster/commit/5875f3bfa98cb44ba2d1edfd7c2dcaa9e50288e6
