### ISSUE TITLE
Support voor onbeschikbaarheid rooster

### ISSUE THREAD

**Issue by matthijs186** [HetIsNiels/ndat-rooster#21]
Het is handig als de website een melding of iets dergelijks laat zien als WebUntis niet beschikbaar is. Op dit moment hebben ze bijvoorbeeld problemen met hoge workloads. Ook al wordt er een uitroepteken weergegeven, is dit toch niet duidelijk genoeg omdat dat ook kan betekenen dat er helemaal geen les is op die dag.

**Comment by nielsvanvelzen** [comment]
fixed
