### ISSUE TITLE
[Feature] Voeg een favicon toe

### ISSUE THREAD

**Issue by matthijs186** [HetIsNiels/ndat-rooster#5]
Zie titel.

Alles moet mooi :>

**Comment by nielsvanvelzen** [comment]
Als iemand een 512x512 icon heeft zou ik een iconset kunnen maken.

**Comment by matthijs186** [comment]
Dit kan werken.
![Rooster icoon](https://pbs.twimg.com/profile_images/1803756502/Icon512.png)

**Comment by RichardWolvekamp** [comment]
Als je de favicon en icon ideeën doorgeeft kan ik er straks even naar kijken

**Comment by nielsvanvelzen** [comment]
![image](https://cloud.githubusercontent.com/assets/2305178/15213294/9cd6a140-1846-11e6-9239-900af4447ecf.png)
From @RichardWolvekamp

**Comment by nielsvanvelzen** [comment]
@RichardWolvekamp moet nog een versie maken zonder achtergrond voor o.a. windows phone

**Comment by nielsvanvelzen** [comment]
fixed doei
