### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by tkrns** [HetIsNiels/ndat-rooster#8]
Pls fix styling

**Comment by matthijs186** [comment]
Please fix the styling of your issue.

**Comment by nielsvanvelzen** [comment]
please fix
![image](https://cloud.githubusercontent.com/assets/2305178/15210083/d7fccd10-1834-11e6-85aa-df11d4fdae16.png)

**Comment by nielsvanvelzen** [comment]
Basis styling is er nu
![image](https://cloud.githubusercontent.com/assets/2305178/15468347/1f8dd77a-20e4-11e6-8577-b2cee87854f9.png)
Meer komt er nog

**Comment by nielsvanvelzen** [comment]
Done
